##Script to explain step by step how to paper a house and what tools are needed unless I decide to split that up also
import time
print('Welcome to the Papering sections!')
time.sleep(3)
print('Are you ready to get started or do you need a list of tools?')
userInput = input('ready, tools?   ')
time.sleep(1)
if userInput == 'tools':
    time.sleep(2)
    print('You will need a hammer tacker,or cap gun, knife, and paper tape. ')
    time.sleep(2)
    print('You will also need your ladders, pump jacks or man lift')
    time.sleep(2)
    print('Once you have off this you are ready to start. ')
else:
    print('Then lets get started with the paper.')

print('Are you going to be doing this with 1 or 2 people?')
time.sleep(1)
userInput2 = input()
if userInput2 =='1':
    print('Start by unrolling the paper the entire length of the area you are papering.')
    time.sleep(2)
    print('Make sure that you have enough paper to extend atleat 6-8 inches past corners')
    time.sleep(2)
    print('so that you have plenty of room to overlap and tape the next section. ')
    time.sleep(2)
    print('Now we want to start at a corner and keep the bottom of the paper flush with the bottom of the wall')
    time.sleep(3)
    print('It is important that at this time the paper does not go around any corners this will make it very')
    time.sleep(2)
    print('difficult to keep everything straight and tight.')
    time.sleep(2)
    print('After we get the entire run of paper attached to the bottom of the house')
    time.sleep(2)
    print('we want to get around the center of the wall and push the paper up and attach')
    time.sleep(3)
    print('it to the wall so that it is nice and tight. ')
    time.sleep(2)
    print('Now most paper is 8 to 10 feet tall')
    time.sleep(2)
    print('So just go up as high as you can reach.')
    time.sleep(2)
    print('Now just start moving left or right and keep working it up.')
    time.sleep(2)
    print('The key here is to let gravity pull the paper down over your head as')
    time.sleep(3)
    print('you work it up and over. ')
    time.sleep(2)
    print('This will help keep the paper tight and looking professional. ')
    time.sleep(2)
    print('Once you get about half way between the center and the corner if you want ')
    time.sleep(2)
    print('you can drop back to the center and grab you ladder and finish the paper all the way')
    time.sleep(2)
    print('up to the top. ')
    time.sleep(2)
    print('If not just go all the way down and then drop back to the center befor you go around the corner. ')
    time.sleep(3)
    print('After you have the paper attached from the bottom to the top you can')
    time.sleep(3)
    print('swing around the corner and attach it. I do not recommend getting to crazy around the ')
    time.sleep(4)
    print('corner, just enough to keep the wind from blowing it around. ')
    time.sleep(3)
    print('Now you will repeat this process. ')
    time.sleep(3)
    print('The paper must overlap a mimimum of 6 inches. ')
    time.sleep(3)
    print('As you move down the wall tape all of the vertical seams.')
    time.sleep(3)
    print('When you start on the next row of paper and you get the bottom attached ')
    time.sleep(3)
    print('Tape the seam as you go. This will make sure that you do not have to walk back and forth')
    time.sleep(4)
if userInput2 == ('2'):
    print('With 2 people this goes a lot faster.')
    time.sleep(2)
##Everything above this is on my github. I know that I need to change the times and check spelling. 
    print('One person will hold the roll and the other will run the tacker or the cap gun.')
    time.sleep(3)
    print('')
    time.sleep()
    
    
    




